// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHPTbPb-QxACC2vE3B1UY2GnNXQmN_ZvE',
    appId: '1:301059644136:web:56f80e0d3a0a836680075d',
    messagingSenderId: '301059644136',
    projectId: 'aquafeedy',
    authDomain: 'aquafeedy.firebaseapp.com',
    storageBucket: 'aquafeedy.firebasestorage.app',
    measurementId: 'G-0XX9KHRYWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3JO01ArM4gO0_p3xdlkwnPYyOu8WrHrs',
    appId: '1:301059644136:android:f22011e39c59f5fe80075d',
    messagingSenderId: '301059644136',
    projectId: 'aquafeedy',
    storageBucket: 'aquafeedy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANKgr3hzJS7pK2drzNaCUOKMOQluDItK4',
    appId: '1:301059644136:ios:4ee0f5975d26fdb580075d',
    messagingSenderId: '301059644136',
    projectId: 'aquafeedy',
    storageBucket: 'aquafeedy.firebasestorage.app',
    iosBundleId: 'com.example.betaAquafeedy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANKgr3hzJS7pK2drzNaCUOKMOQluDItK4',
    appId: '1:301059644136:ios:4ee0f5975d26fdb580075d',
    messagingSenderId: '301059644136',
    projectId: 'aquafeedy',
    storageBucket: 'aquafeedy.firebasestorage.app',
    iosBundleId: 'com.example.betaAquafeedy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHPTbPb-QxACC2vE3B1UY2GnNXQmN_ZvE',
    appId: '1:301059644136:web:ce475f0da4f0bc3980075d',
    messagingSenderId: '301059644136',
    projectId: 'aquafeedy',
    authDomain: 'aquafeedy.firebaseapp.com',
    storageBucket: 'aquafeedy.firebasestorage.app',
    measurementId: 'G-LD0W6HGDKQ',
  );
}
